name: "Dev Infrastructure Destroy"
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  destroy:
    name: "Terraform Destroy Dev"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_DEV_STATE_BUCKET }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ secrets.AWS_DEV_LOCKS_TABLE }}"
      - run: terraform destroy -auto-approve
